version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: arpan1904/todo-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
      - PORT=5000
      - JWT_SECRET=1234
      - EMAIL=arpanbagadia@gmail.com
      - EMAIL_PASS=ldih gzbc zifs tmtg
    depends_on:
      - mongo

  frontend:
    image: arpan1904/todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
